package kotliquery

import kotliquery.LoanPattern.using
import kotliquery.action.ExecuteQueryAction
import kotliquery.action.ListResultQueryAction
import kotliquery.action.NullableResultQueryAction
import kotliquery.action.UpdateAndReturnGeneratedKeyQueryAction
import kotliquery.action.UpdateQueryAction
import org.slf4j.LoggerFactory
import java.io.Closeable
import java.io.InputStream
import java.math.BigDecimal
import java.net.URL
import java.sql.PreparedStatement
import java.sql.SQLException
import java.sql.Statement
import java.time.Instant
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime
import java.time.OffsetDateTime
import java.time.ZonedDateTime

/**
 * Database Session.
 */
open class Session(
    open val connection: Connection,
    open val returnGeneratedKeys: Boolean = true,
    open val autoGeneratedKeys: List<String> = listOf(),
    var transactional: Boolean = false,
    open val strict: Boolean = false,
    open val queryTimeout: Int? = null,
) : Closeable {
    override fun close() {
        transactional = false
        connection.close()
    }

    private val logger = LoggerFactory.getLogger(Session::class.java)

    private inline fun <reified T> PreparedStatement.setTypedParam(
        idx: Int,
        param: Parameter<T>,
    ) {
        if (param.value == null) {
            this.setNull(idx, param.sqlType())
        } else {
            setParam(idx, param.value)
        }
    }

    private fun unwrap(v: Any?): Any? =
        if (v == null) {
            null
        } else {
            when (v) {
                is SqlValued<*> -> v.sqlValue()
                else -> v
            }
        }

    private fun PreparedStatement.setParam(
        idx: Int,
        v: Any?,
    ) {
        if (v == null) {
            this.setObject(idx, null)
        } else {
            val unwrappedValue = unwrap(v)
            when (unwrappedValue) {
                is String -> this.setString(idx, unwrappedValue)
                is Byte -> this.setByte(idx, unwrappedValue)
                is Boolean -> this.setBoolean(idx, unwrappedValue)
                is Int -> this.setInt(idx, unwrappedValue)
                is Long -> this.setLong(idx, unwrappedValue)
                is Short -> this.setShort(idx, unwrappedValue)
                is Double -> this.setDouble(idx, unwrappedValue)
                is Float -> this.setFloat(idx, unwrappedValue)
                is ZonedDateTime -> this.setTimestamp(idx, java.sql.Timestamp.from(unwrappedValue.toInstant()))
                is OffsetDateTime -> this.setTimestamp(idx, java.sql.Timestamp.from(unwrappedValue.toInstant()))
                is Instant -> this.setTimestamp(idx, java.sql.Timestamp.from(unwrappedValue))
                is LocalDateTime -> this.setTimestamp(idx, java.sql.Timestamp.valueOf(unwrappedValue))
                is LocalDate -> this.setDate(idx, java.sql.Date.valueOf(unwrappedValue))
                is LocalTime -> this.setTime(idx, java.sql.Time.valueOf(unwrappedValue))
                is java.sql.Timestamp -> this.setTimestamp(idx, unwrappedValue) // extends java.util.Date
                is java.sql.Time -> this.setTime(idx, unwrappedValue)
                is java.sql.Date -> this.setDate(idx, unwrappedValue)
                is java.sql.SQLXML -> this.setSQLXML(idx, unwrappedValue)
                is java.util.Date -> this.setTimestamp(idx, java.sql.Timestamp(unwrappedValue.time))
                is ByteArray -> this.setBytes(idx, unwrappedValue)
                is InputStream -> this.setBinaryStream(idx, unwrappedValue)
                is BigDecimal -> this.setBigDecimal(idx, unwrappedValue)
                is java.sql.Array -> this.setArray(idx, unwrappedValue)
                is URL -> this.setURL(idx, unwrappedValue)
                // java.util.UUID should be set via setObject
                else -> this.setObject(idx, unwrappedValue)
            }
        }
    }

    fun createArrayOf(
        typeName: String,
        items: Collection<Any>,
    ): java.sql.Array = connection.underlying.createArrayOf(typeName, items.toTypedArray())

    fun populateParams(
        query: Query,
        stmt: PreparedStatement,
    ): PreparedStatement {
        if (query.replacementMap.isNotEmpty()) {
            query.replacementMap.forEach { paramName, occurrences ->
                occurrences.forEach {
                    stmt.setTypedParam(it + 1, query.paramMap[paramName].param())
                }
            }
        } else {
            query.params.forEachIndexed { index, value ->
                stmt.setTypedParam(index + 1, value.param())
            }
        }

        return stmt
    }

    fun createPreparedStatement(query: Query): PreparedStatement {
        val stmt =
            if (returnGeneratedKeys) {
                if (connection.driverName == "oracle.jdbc.driver.OracleDriver") {
                    connection.underlying.prepareStatement(query.cleanStatement, autoGeneratedKeys.toTypedArray())
                } else {
                    connection.underlying.prepareStatement(query.cleanStatement, Statement.RETURN_GENERATED_KEYS)
                }
            } else {
                connection.underlying.prepareStatement(query.cleanStatement)
            }

        if (queryTimeout != null) {
            stmt.queryTimeout = queryTimeout!!
        }

        return populateParams(query, stmt)
    }

    private fun <A> rows(
        query: Query,
        extractor: (Row) -> A?,
    ): List<A> =
        using(createPreparedStatement(query)) { stmt ->
            using(stmt.executeQuery()) { rs ->
                val rows = Row(rs).map { row -> extractor.invoke(row) }
                rows.filter { r -> r != null }.map { r -> r!! }.toList()
            }
        }

    private fun rowsBatched(
        statement: String,
        params: Collection<Collection<Any?>>,
        namedParams: Collection<Map<String, Any?>>,
    ): List<Int> =
        using(connection.underlying.prepareStatement(Query(statement).cleanStatement)) { stmt ->
            if (queryTimeout != null) {
                stmt.queryTimeout = queryTimeout!!
            }
            batchUpdates(namedParams, statement, stmt, params)
            stmt.executeBatch().toList()
        }

    private fun rowsBatchedReturningGeneratedKeys(
        statement: String,
        params: Collection<Collection<Any?>>,
        namedParams: Collection<Map<String, Any?>>,
    ): List<Long> =
        using(
            connection.underlying.prepareStatement(
                Query(statement).cleanStatement,
                Statement.RETURN_GENERATED_KEYS,
            ),
        ) { stmt ->
            batchUpdates(namedParams, statement, stmt, params)
            if (queryTimeout != null) {
                stmt.queryTimeout = queryTimeout!!
            }
            stmt.executeBatch()
            val generatedKeysRs = stmt.generatedKeys
            val keys = mutableListOf<Long>()
            while (generatedKeysRs.next()) {
                keys.add(generatedKeysRs.getLong(1))
            }
            if (keys.isEmpty()) {
                logger.warn("Unexpectedly, Statement#getGeneratedKeys doesn't have any elements for $statement")
            }
            keys.toList()
        }

    private fun batchUpdates(
        namedParams: Collection<Map<String, Any?>>,
        statement: String,
        stmt: PreparedStatement,
        params: Collection<Collection<Any?>>,
    ) {
        if (namedParams.isNotEmpty()) {
            val extracted = Query.extractNamedParamsIndexed(statement)
            namedParams.forEach { paramRow ->
                extracted.forEach { paramName, occurrences ->
                    occurrences.forEach {
                        stmt.setTypedParam(it + 1, paramRow[paramName].param())
                    }
                }
                stmt.addBatch()
            }
        } else {
            params.forEach { paramsRow ->
                paramsRow.forEachIndexed { idx, value ->
                    stmt.setTypedParam(idx + 1, value.param())
                }
                stmt.addBatch()
            }
        }
    }

    private fun warningForTransactionMode() {
        if (transactional) {
            logger.warn("Use TransactionalSession instead. The `tx` of `session.transaction { tx -> ... }`")
        }
    }

    fun <A> single(
        query: Query,
        extractor: (Row) -> A?,
    ): A? {
        warningForTransactionMode()
        val rs = rows(query, extractor)

        return if (strict) {
            when (rs.size) {
                1 -> rs.first()
                0 -> null
                else -> throw SQLException("Expected 1 row but received ${rs.size}.")
            }
        } else {
            if (rs.isNotEmpty()) rs.first() else null
        }
    }

    fun <A> list(
        query: Query,
        extractor: (Row) -> A?,
    ): List<A> {
        warningForTransactionMode()
        return rows(query, extractor).toList()
    }

    fun batchPreparedNamedStatement(
        statement: String,
        params: Collection<Map<String, Any?>>,
    ): List<Int> {
        warningForTransactionMode()
        return rowsBatched(statement, emptyList(), params)
    }

    fun batchPreparedNamedStatementAndReturnGeneratedKeys(
        statement: String,
        params: Collection<Map<String, Any?>>,
    ): List<Long> {
        warningForTransactionMode()
        return rowsBatchedReturningGeneratedKeys(statement, emptyList(), params)
    }

    fun batchPreparedStatement(
        statement: String,
        params: Collection<Collection<Any?>>,
    ): List<Int> {
        warningForTransactionMode()
        return rowsBatched(statement, params, emptyList())
    }

    fun batchPreparedStatementAndReturnGeneratedKeys(
        statement: String,
        params: Collection<Collection<Any?>>,
    ): List<Long> {
        warningForTransactionMode()
        return rowsBatchedReturningGeneratedKeys(statement, params, emptyList())
    }

    fun forEach(
        query: Query,
        operator: (Row) -> Unit,
    ) {
        warningForTransactionMode()
        using(createPreparedStatement(query)) { stmt ->
            using(stmt.executeQuery()) { rs ->
                Row(rs).forEach { row -> operator.invoke(row) }
            }
        }
    }

    fun execute(query: Query): Boolean {
        warningForTransactionMode()
        return using(createPreparedStatement(query)) { stmt ->
            stmt.execute()
        }
    }

    fun update(query: Query): Int {
        warningForTransactionMode()
        return using(createPreparedStatement(query)) { stmt ->
            stmt.executeUpdate()
        }
    }

    fun updateAndReturnGeneratedKey(query: Query): Long? {
        warningForTransactionMode()
        return using(createPreparedStatement(query)) { stmt ->
            if (stmt.executeUpdate() > 0) {
                val rs = stmt.generatedKeys
                val hasNext = rs.next()
                if (!hasNext) {
                    logger.warn("Unexpectedly, Statement#getGeneratedKeys doesn't have any elements for " + query.statement)
                }
                rs.getLong(1)
            } else {
                null
            }
        }
    }

    fun run(action: ExecuteQueryAction): Boolean = action.runWithSession(this)

    fun run(action: UpdateQueryAction): Int = action.runWithSession(this)

    fun run(action: UpdateAndReturnGeneratedKeyQueryAction): Long? = action.runWithSession(this)

    fun <A> run(action: ListResultQueryAction<A>): List<A> = action.runWithSession(this)

    fun <A> run(action: NullableResultQueryAction<A>): A? = action.runWithSession(this)

    inline fun <A> transaction(operation: (TransactionalSession) -> A): A {
        var shouldCommit = true
        try {
            connection.begin()
            transactional = true
            val tx = TransactionalSession(connection, returnGeneratedKeys, autoGeneratedKeys, strict)
            return operation.invoke(tx)
        } catch (e: Exception) {
            shouldCommit = false
            connection.rollback()
            throw e
        } finally {
            if (shouldCommit) {
                connection.commit()
            }
            transactional = false
        }
    }
}
